### PR TITLE
extend @Contract annotation to build contract classes to one file

### PR DESCRIPTION
**Pull request by BigMichi1**
this pull request extends the generation of the Contract classes into one if the name of the Contract class is the same, if they are not the same they are put into separate classes

### CODE REVIEW

**Comment by jakenjarvis** [comment]
Hello, @BigMichi1.
I would like to thank your contribution.(I do not look carefully the changes yet.)

Your idea is great. However, I felt a sense of discomfort. It is the next point.
- Similar logic is seen here and there. Because I think future maintenance is very troublesome, you need to organize.
- Probably, SuperContract annotation is not required. It would be possible to integrate the Contract annotation.
- Appropriate naming? This is not a super class. This is a static inner class.(This may be a matter of my English. I do not understand the nuances correctly?)

I can not accept your code. If I accept your code, I have to fix many later. In this case, your contribution is not left almost... So, I do not want it.
To leave as contributors your name, can you fix this issues? If you can fix this, I would gladly accept your code. ;)

Again, I would like to thank your contribution!

---

My native language is Japanese. Support of a foreign language is not sufficient.
I'm using a machine translation. Please write in English polite. Ability of my English is not high. XD

**Comment by BigMichi1** [comment]
yes you are right i had the same feeling about it after rethink of the Annotation so i made a new one and brought all together in the contract annotation

**Comment by jakenjarvis** [comment]
I appreciate your work! Your work is completed, please contact me.

**Comment by BigMichi1** [comment]
from my point of view it's done, the only problem is travis-ci but i verified that this has nothing to do with the new code. see here: http://wildfly.bigmichi1.de/jenkins/job/Android-OrmLiteContentProvider/30/

**Comment by jakenjarvis** [comment]
It has become a great code than I was expecting. I received it in my develop_jaken branch.
I am very grateful to you!

**Pull request closed without merging**
